# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
  [
    [1, 2, 3],
    [4, 5 ,6],
    [7, 8, 9]
  ],
  [
    [10, 11, 12],
    [13, 14 ,15],
    [16, 17, 18]
  ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), array([1, 2, 3]), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)


((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created


In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
range_array2 = np.random.randint(10, size=(7, 2))
range_array2

array([[5, 2],
       [7, 0],
       [3, 5],
       [9, 3],
       [9, 9],
       [7, 5],
       [3, 8]], dtype=int32)

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 5))

array([[0.75739631, 0.92099388, 0.36257297, 0.8567213 , 0.35292798],
       [0.94912913, 0.93301213, 0.73177744, 0.76333337, 0.00391279],
       [0.67556479, 0.37765434, 0.4857654 , 0.47350197, 0.89611395]])

In [ ]:
np.eye(5) #I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(10, size=(4, 6))
print(random_array)

# Find the unique numbers in the array you just created
np.unique(random_array)


[[1 4 7 9 8 8]
 [0 8 6 8 7 0]
 [7 7 2 0 7 2]
 [2 0 4 9 6 9]]


array([0, 1, 2, 4, 6, 7, 8, 9], dtype=int32)

In [33]:
# Find the 0'th index of the latest array you created
random_array[0]

array([1, 4, 7, 9, 8, 8], dtype=int32)

In [31]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[1, 4, 7, 9, 8, 8],
       [0, 8, 6, 8, 7, 0]], dtype=int32)

In [34]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[1, 4],
       [0, 8]], dtype=int32)

In [49]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_1 = np.random.randint(10, size=(3, 5))
random_array_2 = np.ones((3, 5))

In [47]:
random_array_1

array([[0, 2, 9, 7, 5],
       [7, 8, 3, 0, 0],
       [9, 3, 6, 1, 2]], dtype=int32)

In [48]:
random_array_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# Add the two arrays together
random_added_arrays = random_array_1 + random_array_2
random_added_arrays

array([[1., 5., 1., 8., 1.],
       [1., 2., 2., 6., 7.],
       [5., 1., 1., 3., 2.]])

In [52]:
# Create another array of ones of shape (5, 3)
ones_array = np.ones((5, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
# Try add the array of ones and the other most recent array together
ones_array + random_array_1

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [55]:
# Create another array of ones of shape (3, 5)
ones_2 = np.ones((3, 5))
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# Subtract the new array of ones from the other most recent array
random_array_1 - ones_2

array([[-1.,  3., -1.,  6., -1.],
       [-1.,  0.,  0.,  4.,  5.],
       [ 3., -1., -1.,  1.,  0.]])

In [57]:
# Multiply the ones array with the latest array
random_array_1 * ones_2

array([[0., 4., 0., 7., 0.],
       [0., 1., 1., 5., 6.],
       [4., 0., 0., 2., 1.]])

In [58]:
# Take the latest array to the power of 2 using '**'
random_array_1 ** 2

array([[ 0, 16,  0, 49,  0],
       [ 0,  1,  1, 25, 36],
       [16,  0,  0,  4,  1]], dtype=int32)

In [59]:
# Do the same thing with np.square()
np.square(random_array_1)

array([[ 0, 16,  0, 49,  0],
       [ 0,  1,  1, 25, 36],
       [16,  0,  0,  4,  1]], dtype=int32)

In [60]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_1)

np.float64(2.066666666666667)

In [61]:
# Find the maximum of the latest array using np.max()
np.max(random_array_1)

np.int32(7)

In [62]:
# Find the minimum of the latest array using np.min()
np.min(random_array_1)

np.int32(0)

In [64]:
# Find the standard deviation of the latest array
np.std(random_array_1)

np.float64(2.379542439676633)

In [65]:
# Find the variance of the latest array
np.var(random_array_1)

np.float64(5.662222222222224)

In [71]:
# Reshape the latest array to (3, 5, 1)
reshape_array = random_array_1.reshape((3, 5, 1))
reshape_array

array([[[0],
        [4],
        [0],
        [7],
        [0]],

       [[0],
        [1],
        [1],
        [5],
        [6]],

       [[4],
        [0],
        [0],
        [2],
        [1]]], dtype=int32)

In [77]:
# Transpose the latest array
np.transpose(reshape_array, axes=(1, 0, 2))

array([[[0],
        [0],
        [4]],

       [[4],
        [1],
        [0]],

       [[0],
        [1],
        [0]],

       [[7],
        [5],
        [2]],

       [[0],
        [6],
        [1]]], dtype=int32)

What does the transpose do?

In [80]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_3 = np.random.randint(0, 10, (3, 3))
random_array_4 = np.random.randint(0, 10, (3, 2))

In [81]:
# Perform a dot product on the two newest arrays you created
dot_product_result = np.dot(random_array_3, random_array_4)
random_array_3, random_array_4, dot_product_result

(array([[6, 3, 6],
        [7, 0, 5],
        [7, 4, 3]], dtype=int32),
 array([[1, 5],
        [5, 0],
        [8, 5]], dtype=int32),
 array([[69, 60],
        [47, 60],
        [51, 50]], dtype=int32))

In [85]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_5 = np.random.randint(0, 10, (4, 3))
array_6 = np.random.randint(0, 10, (4, 3))

In [86]:
# Perform a dot product on the two newest arrays you created
dot_product_result_2 = np.dot(array_5, array_6)
array_5, array_6, dot_product_result_2

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [87]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

# Transpose one of the arrays (array_6)
array_6_transposed = array_6.T

# Perform a dot product on the transposed and original arrays
dot_product_result_2 = np.dot(array_5, array_6_transposed)

array_5, array_6, array_6_transposed, dot_product_result_2

(array([[1, 0, 4],
        [4, 6, 8],
        [8, 2, 2],
        [2, 3, 7]], dtype=int32),
 array([[5, 7, 0],
        [7, 3, 0],
        [7, 3, 5],
        [7, 3, 2]], dtype=int32),
 array([[5, 7, 7, 7],
        [7, 3, 3, 3],
        [0, 0, 5, 2]], dtype=int32),
 array([[ 5,  7, 27, 15],
        [62, 46, 86, 62],
        [54, 62, 72, 66],
        [31, 23, 58, 37]], dtype=int32))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [88]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_7 = np.random.randint(0, 10, size=(6, 10))
array_8 = np.random.randint(0, 10, size=(6, 10))

In [89]:
# Compare the two arrays with '>'
array_7 > array_8

array([[ True, False,  True, False, False, False,  True, False,  True,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False,  True,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True,  True, False, False, False, False,
        False],
       [False, False,  True, False, False, False,  True,  True, False,
         True]])

What happens when you compare the arrays with `>`?

In [90]:
# Compare the two arrays with '>='
array_7 >= array_8

array([[ True, False,  True,  True, False, False,  True, False,  True,
        False],
       [ True, False,  True, False, False,  True, False,  True, False,
        False],
       [False, False, False, False, False, False,  True, False,  True,
         True],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True,  True, False, False, False, False,
         True],
       [False,  True,  True, False, False, False,  True,  True, False,
         True]])

In [91]:
# Find which elements of the first array are greater than 7
array_5 > 7

array([[False, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False]])

In [93]:
# Which parts of each array are equal? (try using '==')
array_5, array_6, array_5 == array_6

(array([[1, 0, 4],
        [4, 6, 8],
        [8, 2, 2],
        [2, 3, 7]], dtype=int32),
 array([[5, 7, 0],
        [7, 3, 0],
        [7, 3, 5],
        [7, 3, 2]], dtype=int32),
 array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False]]))

In [94]:
# Sort one of the arrays you just created in ascending order
np.sort(array_5)

array([[0, 1, 4],
       [4, 6, 8],
       [2, 2, 8],
       [2, 3, 7]], dtype=int32)

In [99]:
# Sort the indexes of one of the arrays you just created
array_5.flatten(), np.argsort(array_5.flatten())

(array([1, 0, 4, 4, 6, 8, 8, 2, 2, 2, 3, 7], dtype=int32),
 array([ 1,  0,  7,  8,  9, 10,  3,  2,  4, 11,  6,  5]))

In [102]:
# Find the index with the maximum value in one of the arrays you've created
array_5, np.argmax(array_5), array_5.shape, np.unravel_index(np.argmax(array_5), array_5.shape)

(array([[1, 0, 4],
        [4, 6, 8],
        [8, 2, 2],
        [2, 3, 7]], dtype=int32),
 np.int64(5),
 (4, 3),
 (np.int64(1), np.int64(2)))

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_5), array_5.shape, np.unravel_index(np.argmin(array_5), array_5.shape)

(np.int64(0), np.int64(1))

In [105]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
array_5, np.argmax(array_5, axis=1)

(array([[1, 0, 4],
        [4, 6, 8],
        [8, 2, 2],
        [2, 3, 7]], dtype=int32),
 array([2, 2, 0, 2]))

In [106]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
# Find the indexes of the minimum values along the 0th axis (columns) of array_5
min_indexes_axis_0 = np.argmin(array_5, axis=0)
array_5, min_indexes_axis_0

(array([[1, 0, 4],
        [4, 6, 8],
        [8, 2, 2],
        [2, 3, 7]], dtype=int32),
 array([0, 0, 2]))

In [107]:
# Create an array of normally distributed random numbers
np.random.randn(4, 4)

array([[-2.02514259,  0.18645431, -0.66178646,  0.85243333],
       [-0.79252074, -0.11473644,  0.50498728,  0.86575519],
       [-1.20029641, -0.33450124, -0.47494531, -0.65332923],
       [ 1.76545424,  0.40498171, -1.26088395,  0.91786195]])

In [108]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.